week_1

<li>Have students listen to each word and repeat it at least three times (if possible, have students do actions for the words)<br/></li>

<li>Have students listen to each word and repeat it at least three times (if possible, have students do actions for the words)<br/></li><li>After going through all the words, have students listen and repeat each word again, at a faster pace.<br/></li>

<li>Have students listen to each word and repeat it at least three times (if possible, have students do actions for the words)<br/></li><li>After going through all the words, have students listen and repeat each word again, at a faster pace.<br/></li><li>Listen for words that students are having trouble with and spend extra time on those.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Run &amp; Touch</span><span style="font-size:10;"><br/>Select 3-4 students to come and stand a few meters away from the board. When you say a word, the students should run and touch the picture on the board (saying the word as they run). Your co-teacher should encourage the sitting students to also say the word. After a few turns, select another group of students to play. Keep it fast-paced!</span><span style="font-size:10;"><br/></span></li>

<li>Encourage the whole class to say the words as you point to the pictures on the board, then tap the pictures to check.<br/></li>

<li>Encourage the whole class to say the words as you point to the pictures on the board, then tap the pictures to check.<br/></li><li>Tap </span><span style="font-size:10;"><b>RESET</b></span><span style="font-size:10;"> and repeat.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Jump to the Lines</span><span style="font-size:10;"><br/>Use some colored tape to make four lines on the floor. Place a basket by the last line. Invite 3-4 students to stand at the first line and give each student a ball. When you point to the first picture on the board, students should jump to the next line as they say the word. Repeat. When students reach the last line, they can throw their balls into the basket. Tap </span><span style="font-size:10;"><b>RESET</b></span><span style="font-size:10;"> and invite a different group of students to play.</span></li>

<li>Point to a picture and have students say the word, then tap the picture and move to the next one.</li><li>Continue, until there are no more pictures on the screen.<br/></li>

<li>Point to a picture and have students say the word, then tap the picture and move to the next one.</li><li>Continue, until there are no more pictures on the screen.<br/></li><li>Tap </span><span style="font-size:10;"><b>RESET</b></span><span style="font-size:10;"> to show more pictures.</span><span style="text-decoration: underline;font-size:10;"><br/>Play a Game: Timed Relay (2 Teams)</span><span style="font-size:10;"><br/>Tap the </span><span style="font-size:10;"><b>TIMER</b></span><span style="font-size:10;"> in the toolbar to enable the timer. Divide the class into two teams (with students of mixed abilities in each team). One team plays at a time. When you start the timer, students in one team take turns to run to the board, say a word and tap the picture. When all the pictures have been tapped, record the time, then invite the next team to play. When the second team has finished, compare times. Play again.<br/>TIP: To make sure students SAY the words, make a rule that if students do not say each word before tapping it, the other team automatically wins.</span></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to highlight a different word. Ask students: 'What's this?'.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to highlight a different word. Ask students: 'What's this?'.<br/></li><li>Click the picture to check and have the whole class repeat the sentence.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to highlight a different word. Ask students: 'What's this?'.<br/></li><li>Click the picture to check and have the whole class repeat the sentence.<br/></li><li>Continue.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to highlight a different word. Ask students: 'What's this?'.<br/></li><li>Click the picture to check and have the whole class repeat the sentence.<br/></li><li>Continue.<br/></li><li>As students develop confidence, have the whole class produce the sentences without listening first.<br/></li><li>Finally, have students take turns to say the sentences individually.</span></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to highlight a different word. Ask students: 'What's this?'.<br/></li><li>Click the picture to check and have the whole class repeat the sentence.<br/></li><li>Continue.<br/></li><li>As students develop confidence, have the whole class produce the sentences without listening first.<br/></li>

<li>Understand the meaning of the dialogue and language structures<br/></li>

<li>Understand the meaning of the dialogue and language structures<br/></li><li>Listen to and repeat the </span><span style="font-size:10;"><i>response</i></span><span style="font-size:10;">part of the dialogue with correct pronunciation and intonation</span></li>

<li>Allow students to listen to the dialogue.<br/></li>

<li>Allow students to listen to the dialogue.<br/></li><li>Use actions and expressive voice to help students understand the meaning of the language.<br/></li><li>Encourage students to repeat the response part of the dialogue, with actions.<br/></li>

<li>Allow students to listen to the dialogue.<br/></li><li>Use actions and expressive voice to help students understand the meaning of the language.<br/></li><li>Encourage students to repeat the response part of the dialogue, with actions.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT </b></span><span style="font-size:10;">for more dialogues.</span></li>

<li>Allow students to listen to the dialogue.<br/></li><li>Use actions and expressive voice to help students understand the meaning of the language.<br/></li>

<li></span><span style="font-size:10;"><i>Respond</i></span><span style="font-size:10;">to questions with correct pronunciation and language structures<br/></li>

<li></span><span style="font-size:10;"><i>Respond</i></span><span style="font-size:10;">to questions with correct pronunciation and language structures<br/></li><li>Develop confidence and fluency in spoken language</span></li>

<li>Have students listen to the question, then guide them to say the correct response (as a whole class). Click the character (or speech bubble) to check.<br/></li>

<li>Have students listen to the question, then guide them to say the correct response (as a whole class). Click the character (or speech bubble) to check.<br/></li><li>Click </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> and repeat. Continue until students show enough confidence to play a game.<br/></span><span style="text-decoration: underline;font-size:10;">Play a game: Telephone Race</span><span style="font-size:10;"><br/>Divide the class into two teams, with each team sitting in a line. One teacher guides each team (both teams play at the same time). Whisper the sentence to the first student in the lin</span><span style="font-size:10;">e </span><span style="font-size:10;">(e.g. ‘My name is Tom’).</span><span style="font-size:10;"> That student then turns and whispers it to their neighbor, and so on, down the line. When the sentence reaches the last student in the line, they should shout out the sentence and run to the board to touch the character. After one round, have students shuffle the in their seats, so that a different student can be the last in the line.<br/>NOTE: The first time you play the game, be sure to model how to play first.<br/></span></li>

<li>Apply language structures to </span><span style="font-size:10;"><i>express own ideas</i></span><span style="font-size:10;"><br/></li>

<li>Apply language structures to </span><span style="font-size:10;"><i>express own ideas</i></span><span style="font-size:10;"><br/></li><li>Demonstrate mastery of language structures</span></li>

<li>Wave and say 'hello' to one of the characters on the screen, then ask 'what's your name?'.<br/></li>

<li>Wave and say 'hello' to one of the characters on the screen, then ask 'what's your name?'.<br/></li><li>Encourage students to say the sentence (e.g. 'My name is Tom'), then tap the character to check.<br/></li>

<li>Wave and say 'hello' to one of the characters on the screen, then ask 'what's your name?'.<br/></li><li>Encourage students to say the sentence (e.g. 'My name is Tom'), then tap the character to check.<br/></li><li>Repeat for all characters on the screen.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Pass the Ball (Part 1)</span><span style="font-size:10;"><br/>Hold a ball and say your name, then pass the ball to your co-teacher and have them do the same. Repeat if necessary. Pass the ball around the room and have each student say their name as they hold the ball.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Pass the Ball (Part 2)</span><span style="font-size:10;"><br/>Hold the ball and say: 'My name is [own name]', then pass the ball to your co-teacher and have them do the same. Repeat if necessary. Pass the ball around the room and have each student say: 'My name is [own name]' as they hold the ball. Finally, invite students to the front of the class to introduce themselves, using the sentence frame: 'Hello. My name is ___'.</span></li>

<li>Tap the speaker and guide students to listen to the first sound of the word.<br/></li>

<li>Tap the speaker and guide students to listen to the first sound of the word.<br/></li><li>If the word starts with the sound of the day, encourage students to say the sound (and do the action for the sound).<br/></li>

<li>Tap the speaker and guide students to listen to the first sound of the word.<br/></li><li>If the word starts with the sound of the day, encourage students to say the sound (and do the action for the sound).<br/></li><li>If the word does not start with the sound of the day, encourage students to say: ‘NO’.<br/></li>

<li>Tap the speaker and guide students to listen to the first sound of the word.<br/></li><li>If the word starts with the sound of the day, encourage students to say the sound (and do the action for the sound).<br/></li><li>If the word does not start with the sound of the day, encourage students to say: ‘NO’.<br/></li><li>Depending on the first sound of the word, tap the word of the day or the bin at the bottom of the screen.<br/></li>

<li>Tap the speaker and guide students to listen to the first sound of the word.<br/></li><li>If the word starts with the sound of the day, encourage students to say the sound (and do the action for the sound).<br/></li><li>If the word does not start with the sound of the day, encourage students to say: ‘NO’.<br/></li><li>Depending on the first sound of the word, tap the word of the day or the bin at the bottom of the screen.<br/></li><li>Click the speaker again and continue.<br/></li>

<li>Tap the speaker and guide students to listen to the first sound of the word.<br/></li><li>If the word starts with the sound of the day, encourage students to say the sound (and do the action for the sound).<br/></li><li>If the word does not start with the sound of the day, encourage students to say: ‘NO’.<br/></li><li>Depending on the first sound of the word, tap the word of the day or the bin at the bottom of the screen.<br/></li><li>Click the speaker again and continue.<br/></li><li>Tap </span><span style="font-size:10;"><b>RESET</b></span><span style="font-size:10;"> to play again.<br/>TIP: If students are able, have them say the sentence: '[word] starts with [sound]' (e.g. '</span><span style="font-size:10;">Milk</span><span style="font-size:10;"> starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/).<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Sit or Stand</span><span style="font-size:10;"><br/>Tap the speaker to hear a word. If the word begins with the sound of the day, students should stand up and say the sound (and do the action). If the word does not begin with the sound of the day, they should remain sitting and say: ‘No’. Either you or a student can click the correct picture on the screen. Continue.</span></li>

<li>Ask students if they can remember the word of the day, then tap the left curtain to check.<br/></li>

<li>Ask students if they can remember the word of the day, then tap the left curtain to check.<br/></li><li>Ask students if they can remember the sound of the day, then tap the middle curtain to check.<br/></li>

<li>Ask students if they can remember the word of the day, then tap the left curtain to check.<br/></li><li>Ask students if they can remember the sound of the day, then tap the middle curtain to check.<br/></li><li>Ask students if they can guess the letter of the day, then tap the right curtain to check.<br/></li>

<li>Ask students if they can remember the word of the day, then tap the left curtain to check.<br/></li><li>Ask students if they can remember the sound of the day, then tap the middle curtain to check.<br/></li><li>Ask students if they can guess the letter of the day, then tap the right curtain to check.<br/></li><li>Have students repeat the sentence '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/' while doing the action as they say the sound.</span></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class.<br/></li><li>Ask students to recall the letter of the day.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class.<br/></li><li>Ask students to recall the letter of the day.<br/></li><li>Ask students to find the letter of the day in the alphabet on the board.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class.<br/></li><li>Ask students to recall the letter of the day.<br/></li><li>Ask students to find the letter of the day in the alphabet on the board.<br/></li><li>Tap the letter of the day to enlarge it.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class.<br/></li><li>Ask students to recall the letter of the day.<br/></li><li>Ask students to find the letter of the day in the alphabet on the board.<br/></li><li>Tap the letter of the day to enlarge it.<br/></li><li>Tap the 'M' and have students repeat: 'big M'.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class.<br/></li><li>Ask students to recall the letter of the day.<br/></li><li>Ask students to find the letter of the day in the alphabet on the board.<br/></li><li>Tap the letter of the day to enlarge it.<br/></li><li>Tap the 'M' and have students repeat: 'big M'.<br/></li><li>Tap the 'm' and have students repeat: 'small m'.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Jump and Crouch</span><span style="font-size:10;"><br/>Encourage students to say 'big M' and 'small m' as you point to the big and small letters on the board. Students should jump as they say 'big M' and crouch as they say 'small m'.</span></li>

<li>Draw attention to the letters at the bottom of the screen.<br/></li>

<li>Draw attention to the letters at the bottom of the screen.<br/></li><li>Ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'. Encourage students to use the sentence: '</span><span style="font-size:10;">M </span><span style="font-size:10;">sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/'.<br/></li>

<li>Draw attention to the letters at the bottom of the screen.<br/></li><li>Ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'. Encourage students to use the sentence: '</span><span style="font-size:10;">M </span><span style="font-size:10;">sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/'.<br/></li><li>Tell students that we need to listen to the sound (tap the highlighted puzzle piece to hear the audio).<br/></li>

<li>Draw attention to the letters at the bottom of the screen.<br/></li><li>Ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'. Encourage students to use the sentence: '</span><span style="font-size:10;">M </span><span style="font-size:10;">sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/'.<br/></li><li>Tell students that we need to listen to the sound (tap the highlighted puzzle piece to hear the audio).<br/></li><li>If we hear /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, we should say '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/', then we can drag the letter</span><span style="font-size:10;"> M</span><span style="font-size:10;"> to complete the picture.<br/></li>

<li>Draw attention to the letters at the bottom of the screen.<br/></li><li>Ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'. Encourage students to use the sentence: '</span><span style="font-size:10;">M </span><span style="font-size:10;">sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/'.<br/></li><li>Tell students that we need to listen to the sound (tap the highlighted puzzle piece to hear the audio).<br/></li><li>If we hear /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, we should say '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/', then we can drag the letter</span><span style="font-size:10;"> M</span><span style="font-size:10;"> to complete the picture.<br/></li><li>If we hear a different sound, we should say 'NO'.<br/></li>

<li>Draw attention to the letters at the bottom of the screen.<br/></li><li>Ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'. Encourage students to use the sentence: '</span><span style="font-size:10;">M </span><span style="font-size:10;">sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/'.<br/></li><li>Tell students that we need to listen to the sound (tap the highlighted puzzle piece to hear the audio).<br/></li><li>If we hear /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, we should say '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/', then we can drag the letter</span><span style="font-size:10;"> M</span><span style="font-size:10;"> to complete the picture.<br/></li><li>If we hear a different sound, we should say 'NO'.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to continue. Invite students who are participating well to drag the letters.<br/></li>

<li>Draw attention to the letters at the bottom of the screen.<br/></li><li>Ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'. Encourage students to use the sentence: '</span><span style="font-size:10;">M </span><span style="font-size:10;">sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/'.<br/></li><li>Tell students that we need to listen to the sound (tap the highlighted puzzle piece to hear the audio).<br/></li><li>If we hear /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, we should say '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/', then we can drag the letter</span><span style="font-size:10;"> M</span><span style="font-size:10;"> to complete the picture.<br/></li><li>If we hear a different sound, we should say 'NO'.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to continue. Invite students who are participating well to drag the letters.<br/></li><li>Tap </span><span style="font-size:10;"><b>RESET </b></span><span style="font-size:10;">to play again.</span></li>

<li>Tap Sam's hand to reveal a letter. If the letter is </span><span style="font-size:10;">M/m</span><span style="font-size:10;">, ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'<br/></li>

<li>Tap Sam's hand to reveal a letter. If the letter is </span><span style="font-size:10;">M/m</span><span style="font-size:10;">, ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'<br/></li><li>Encourage them to respond: '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/' and click the letter to collect it.<br/></li>

<li>Tap Sam's hand to reveal a letter. If the letter is </span><span style="font-size:10;">M/m</span><span style="font-size:10;">, ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'<br/></li><li>Encourage them to respond: '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/' and click the letter to collect it.<br/></li><li>If a different letter appears, ask students: 'Is this letter </span><span style="font-size:10;">M</span><span style="font-size:10;">?'<br/></li>

<li>Tap Sam's hand to reveal a letter. If the letter is </span><span style="font-size:10;">M/m</span><span style="font-size:10;">, ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'<br/></li><li>Encourage them to respond: '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/' and click the letter to collect it.<br/></li><li>If a different letter appears, ask students: 'Is this letter </span><span style="font-size:10;">M</span><span style="font-size:10;">?'<br/></li><li>Have students respond, then click the hand</span><span style="font-size:10;"><b> </b></span><span style="font-size:10;">again, to reveal another letter.<br/></li>

<li>Tap Sam's hand to reveal a letter. If the letter is </span><span style="font-size:10;">M/m</span><span style="font-size:10;">, ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'<br/></li><li>Encourage them to respond: '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/' and click the letter to collect it.<br/></li><li>If a different letter appears, ask students: 'Is this letter </span><span style="font-size:10;">M</span><span style="font-size:10;">?'<br/></li><li>Have students respond, then click the hand</span><span style="font-size:10;"><b> </b></span><span style="font-size:10;">again, to reveal another letter.<br/></li><li>Invite students who are participating well to come to the board and tap.<br/></li>

<li>Tap Sam's hand to reveal a letter. If the letter is </span><span style="font-size:10;">M/m</span><span style="font-size:10;">, ask students: 'What does </span><span style="font-size:10;">M</span><span style="font-size:10;"> sound like?'<br/></li><li>Encourage them to respond: '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/' and click the letter to collect it.<br/></li><li>If a different letter appears, ask students: 'Is this letter </span><span style="font-size:10;">M</span><span style="font-size:10;">?'<br/></li><li>Have students respond, then click the hand</span><span style="font-size:10;"><b> </b></span><span style="font-size:10;">again, to reveal another letter.<br/></li><li>Invite students who are participating well to come to the board and tap.<br/></li><li>Repeat, until all letters have been filled at the top of the screen.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Class Relay</span><span style="font-size:10;"><br/>Students take turns to come to the board and tap the hand If they see the letter of the day, students should say: '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/' and tap the letter. Students each get one turn to tap the board, then they go back and high-five the next student to come and try.<br/></span></li>

<li>Have students listen to each word and repeat it at least three times (if possible, have students do actions for the words)<br/></li>

<li>Have students listen to each word and repeat it at least three times (if possible, have students do actions for the words)<br/></li><li>After going through all the words, have students listen and repeat each word again, at a faster pace.<br/></li>

<li>Have students listen to each word and repeat it at least three times (if possible, have students do actions for the words)<br/></li><li>After going through all the words, have students listen and repeat each word again, at a faster pace.<br/></li><li>Listen for words that students are having trouble with and spend extra time on those.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Step to the Board</span><span style="font-size:10;"><br/>Tap on a picture and have students repeat the word, while doing the action. Then, students need to stand up and take three steps forward. Each time they take a step, they should say the word and do the action. When students are close to the board, chase them back to their seats. Repeat<br/></span></li>

<li>Allow students to listen and enjoy the story (students should NOT be repeating the sentences at this stage).<br/></li>

<li>Allow students to listen and enjoy the story (students should NOT be repeating the sentences at this stage).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li>

<li>Allow students to listen and enjoy the story (students should NOT be repeating the sentences at this stage).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li><li>Tap </span><span style="font-size:10;"><b>? </b></span><span style="font-size:10;">to access comprehension questions for each page.</span></li>

<li>Encourage students to repeat the sentences on each page (point to the words as the students read them).<br/></li>

<li>Encourage students to repeat the sentences on each page (point to the words as the students read them).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li>

<li>Encourage students to repeat the sentences on each page (point to the words as the students read them).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li><li>Tap</span><span style="font-size:10;"><b> ? </b></span><span style="font-size:10;">to access comprehension questions for each page.</span></li>

<li>Encourage students to repeat the sentences on each page (clearly point to the words as the students read them).<br/></li>

<li>Encourage students to repeat the sentences on each page (clearly point to the words as the students read them).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li>

<li>Encourage students to repeat the sentences on each page (clearly point to the words as the students read them).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li><li>Tap </span><span style="font-size:10;"><b>?</b></span><span style="font-size:10;"> to access comprehension questions for each page.<br/></li>

<li>Encourage students to repeat the sentences on each page (clearly point to the words as the students read them).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li><li>Tap </span><span style="font-size:10;"><b>?</b></span><span style="font-size:10;"> to access comprehension questions for each page.<br/></li><li>Encourage students to find words beginning with </span><span style="font-size:10;">M</span><span style="font-size:10;">.<br/></li>

<li>Encourage students to repeat the sentences on each page (clearly point to the words as the students read them).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li><li>Tap </span><span style="font-size:10;"><b>?</b></span><span style="font-size:10;"> to access comprehension questions for each page.<br/></li><li>Encourage students to find words beginning with </span><span style="font-size:10;">M</span><span style="font-size:10;">.<br/></li><li>Invite students to come to the board and tap the words to collect them.</span></li>

<li>Invite students to drag the pieces to complete the puzzle.<br/></li>

<li>Invite students to drag the pieces to complete the puzzle.<br/></li><li>Draw attention to the grey words, then have students repeat the sentence (point to the words as students say them).<br/></li>

<li>Invite students to drag the pieces to complete the puzzle.<br/></li><li>Draw attention to the grey words, then have students repeat the sentence (point to the words as students say them).<br/></li><li>Ask students: 'What is the first word in the sentence?'.<br/></li>

<li>Invite students to drag the pieces to complete the puzzle.<br/></li><li>Draw attention to the grey words, then have students repeat the sentence (point to the words as students say them).<br/></li><li>Ask students: 'What is the first word in the sentence?'.<br/></li><li>Encourage all students to respond, then invite one student to come the board and drag the word.<br/></li>

<li>Invite students to drag the pieces to complete the puzzle.<br/></li><li>Draw attention to the grey words, then have students repeat the sentence (point to the words as students say them).<br/></li><li>Ask students: 'What is the first word in the sentence?'.<br/></li><li>Encourage all students to respond, then invite one student to come the board and drag the word.<br/></li><li>Repeat for all words.<br/></li>

<li>Invite students to drag the pieces to complete the puzzle.<br/></li><li>Draw attention to the grey words, then have students repeat the sentence (point to the words as students say them).<br/></li><li>Ask students: 'What is the first word in the sentence?'.<br/></li><li>Encourage all students to respond, then invite one student to come the board and drag the word.<br/></li><li>Repeat for all words.<br/></li><li>When complete, tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> for a different page from the story.<br/></span></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li><li>Begin by demonstrating the correct way to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li><li>Begin by demonstrating the correct way to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'.<br/></li><li>Write the letter again, making some silly mistakes (consider stroke order, proportions and position on the lines).<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li><li>Begin by demonstrating the correct way to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'.<br/></li><li>Write the letter again, making some silly mistakes (consider stroke order, proportions and position on the lines).<br/></li><li>Finally, demonstrate again the correct way to write 'big</span><span style="font-size:10;"> M</span><span style="font-size:10;">'.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li><li>Begin by demonstrating the correct way to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'.<br/></li><li>Write the letter again, making some silly mistakes (consider stroke order, proportions and position on the lines).<br/></li><li>Finally, demonstrate again the correct way to write 'big</span><span style="font-size:10;"> M</span><span style="font-size:10;">'.<br/></li><li>Repeat all of the above for 'small </span><span style="font-size:10;">m</span><span style="font-size:10;">'.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li><li>Begin by demonstrating the correct way to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'.<br/></li><li>Write the letter again, making some silly mistakes (consider stroke order, proportions and position on the lines).<br/></li><li>Finally, demonstrate again the correct way to write 'big</span><span style="font-size:10;"> M</span><span style="font-size:10;">'.<br/></li><li>Repeat all of the above for 'small </span><span style="font-size:10;">m</span><span style="font-size:10;">'.<br/></li><li>Stroke Instructions for 'small</span><span style="font-size:10;"> m</span><span style="font-size:10;">': </span><span style="font-size:10;"> 'Down, over, over'.</span></li>

<li>Tap the PEN in the toolbar to enable the pen function.<br/></li>

<li>Tap the PEN in the toolbar to enable the pen function.<br/></li><li>Demonstrate and explain how students should complete the page in their workbooks. As you are doing so, ask the following questions:<br/>Q: What is this? A: </span><span style="font-size:10;">Milk</span><span style="font-size:10;"><br/>Q: What sound does 'milk' start with?  A: </span><span style="font-size:10;">Milk </span><span style="font-size:10;">starts with</span><span style="font-size:10;"> /m/.</span><span style="font-size:10;"><br/>Q: What letter sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/</span><span style="font-size:10;">? A: </span><span style="font-size:10;">M</span></li>

<li>Tap the PEN in the toolbar to enable the pen function.<br/></li>

<li>Tap the PEN in the toolbar to enable the pen function.<br/></li><li>Demonstrate and explain how students should complete the page in their workbooks. As you are doing so, ask the following questions:<br/>Q: What is the letter of the day?' A: </span><span style="font-size:10;">M</span><span style="font-size:10;"><br/>Q: What does</span><span style="font-size:10;"> M</span><span style="font-size:10;"> sound like?  A: </span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/>Q: What does '</span><span style="font-size:10;">milk</span><span style="font-size:10;">' start with'? A: </span><span style="font-size:10;">Milk</span><span style="font-size:10;"> starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/>Q: What letter should we write? A: </span><span style="font-size:10;">M</span></li>

week_2

<li>Have students listen to each word and repeat it at least three times (if possible, have students do actions for the words)<br/></li>

<li>Have students listen to each word and repeat it at least three times (if possible, have students do actions for the words)<br/></li><li>After going through all the words, have students listen and repeat each word again, at a faster pace.<br/></li>

<li>Have students listen to each word and repeat it at least three times (if possible, have students do actions for the words)<br/></li><li>After going through all the words, have students listen and repeat each word again, at a faster pace.<br/></li><li>Listen for words that students are having trouble with and spend extra time on those.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Run &amp; Touch</span><span style="font-size:10;"><br/>Select 3-4 students to come and stand a few meters away from the board. When you say a word, the students should run and touch the picture on the board (saying the word as they run). Your co-teacher should encourage the sitting students to also say the word. After a few turns, select another group of students to play. Keep it fast-paced!<br/></span><span style="font-size:10;"><br/></span></li>

<li>Encourage the whole class to say the words as you point to the pictures on the board, then tap the pictures to check.<br/></li>

<li>Encourage the whole class to say the words as you point to the pictures on the board, then tap the pictures to check.<br/></li><li>Tap </span><span style="font-size:10;"><b>RESET</b></span><span style="font-size:10;"> and repeat.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Jump to the Lines</span><span style="font-size:10;"><br/>Use some colored tape to make four lines on the floor. Place a basket by the last line. Invite 3-4 students to stand at the first line and give each student a ball. When you point to the first picture on the board, students should jump to the next line as they say the word. Repeat. When students reach the last line, they can throw their balls into the basket. Tap </span><span style="font-size:10;"><b>RESET</b></span><span style="font-size:10;"> and invite a different group of students to play.<br/></span></li>

<li>Point to a picture and have students say the word, then tap the picture and move to the next one.<br/></li>

<li>Point to a picture and have students say the word, then tap the picture and move to the next one.<br/></li><li>Continue, until there are no more pictures on the screen.<br/></li>

<li>Point to a picture and have students say the word, then tap the picture and move to the next one.<br/></li><li>Continue, until there are no more pictures on the screen.<br/></li><li>Tap </span><span style="font-size:10;"><b>RESET</b></span><span style="font-size:10;"> to show more pictures.</span><span style="text-decoration: underline;font-size:10;"><br/>Play a Game: Timed Relay (2 Teams)</span><span style="font-size:10;"><br/>Tap the </span><span style="font-size:10;"><b>TIMER</b></span><span style="font-size:10;"> in the toolbar to enable the timer. Divide the class into two teams (with students of mixed abilities in each team). One team plays at a time. When you start the timer, students in one team take turns to run to the board, say a word and tap the picture. When all the pictures have been tapped, record the time, then invite the next team to play. When the second team has finished, compare times. Play again.<br/>TIP: To make sure students SAY the words, make a rule that if students do not say each word before tapping it, the other team automatically wins.</span></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to highlight a different word. Ask students: 'What's this?'.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to highlight a different word. Ask students: 'What's this?'.<br/></li><li>Click the picture to check and have the whole class repeat the sentence.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to highlight a different word. Ask students: 'What's this?'.<br/></li><li>Click the picture to check and have the whole class repeat the sentence.<br/></li><li>Continue.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to highlight a different word. Ask students: 'What's this?'.<br/></li><li>Click the picture to check and have the whole class repeat the sentence.<br/></li><li>Continue.<br/></li><li>As students develop confidence, have the whole class produce the sentences without listening first.<br/></li>

<li>Point to the highlighted picture and ask your co-teacher: 'What's this?'.<br/></li><li>Your co-teacher should use the target language to answer (e.g. 'A table.'), then tap the image to check. Have students repeat the sentence.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to highlight a different word. Ask students: 'What's this?'.<br/></li><li>Click the picture to check and have the whole class repeat the sentence.<br/></li><li>Continue.<br/></li><li>As students develop confidence, have the whole class produce the sentences without listening first.<br/></li><li>Finally, have students take turns to say the sentences individually.</span></li>

<li>Review the meaning of the dialogue and language structures<br/></li>

<li>Review the meaning of the dialogue and language structures<br/></li><li>Listen and repeat </span><span style="font-size:10;"><i>all</i></span><span style="font-size:10;"> parts of the dialogue with correct<br/>    pronunciation and intonatoin</span></li>

<li>Allow students to listen to the dialogue.<br/></li>

<li>Allow students to listen to the dialogue.<br/></li><li>Use actions and expressive voice to help reinforce the meaning of the language.<br/></li>

<li>Allow students to listen to the dialogue.<br/></li><li>Use actions and expressive voice to help reinforce the meaning of the language.<br/></li><li>Encourage students to repeat the question </span><span style="font-size:10;"><i>and</i></span><span style="font-size:10;"> response parts of the dialogue with actions.<br/></li>

<li>Allow students to listen to the dialogue.<br/></li><li>Use actions and expressive voice to help reinforce the meaning of the language.<br/></li><li>Encourage students to repeat the question </span><span style="font-size:10;"><i>and</i></span><span style="font-size:10;"> response parts of the dialogue with actions.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> for more dialogues.</span></li>

<li></span><span style="font-size:10;"><i>Ask </i></span><span style="font-size:10;">and</span><span style="font-size:10;"><i> respond to</i></span><span style="font-size:10;"> questions with correct pronunciation and language structures<br/></li>

<li></span><span style="font-size:10;"><i>Ask </i></span><span style="font-size:10;">and</span><span style="font-size:10;"><i> respond to</i></span><span style="font-size:10;"> questions with correct pronunciation and language structures<br/></li><li>Develop confidence and fluency</span></li>

<li>Guide the whole class to say the question, then click the character (or speech bubble) to check.<br/></li>

<li>Guide the whole class to say the question, then click the character (or speech bubble) to check.<br/></li><li>Guide the whole class to say the response, then click the character (or speech bubble) to check.<br/></li>

<li>Guide the whole class to say the question, then click the character (or speech bubble) to check.<br/></li><li>Guide the whole class to say the response, then click the character (or speech bubble) to check.<br/></li><li>Click </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> and repeat. Continue until students show enough confidence to play a game.<br/></span><span style="text-decoration: underline;font-size:10;">Play a game: Step to the Line</span><span style="font-size:10;"><br/>Divide students into two groups and have them each form a line, standing on opposite sides of the classroom. One group will say the question and the other team will say the response. Draw a line down the center of the room. One teacher stands with the ‘question’ team and encourages them to say the question together. This team then steps to the line. The other teacher guides the 'response' team to say the response together. This team then also steps to the line and high-fives the other group.</span></li>

<li>Apply language structures to </span><span style="font-size:10;"><i>enquire </i></span><span style="font-size:10;">and</span><span style="font-size:10;"><i> express own ideas</i></span><span style="font-size:10;"><br/></li>

<li>Apply language structures to </span><span style="font-size:10;"><i>enquire </i></span><span style="font-size:10;">and</span><span style="font-size:10;"><i> express own ideas</i></span><span style="font-size:10;"><br/></li><li>Demonstrate mastery of language structures</span></li>

<li>Wave and say 'hello' to one of the characters on the screen, then ask 'what's your name?'.<br/></li>

<li>Wave and say 'hello' to one of the characters on the screen, then ask 'what's your name?'.<br/></li><li>Encourage students to repeat the question.<br/></li>

<li>Wave and say 'hello' to one of the characters on the screen, then ask 'what's your name?'.<br/></li><li>Encourage students to repeat the question.<br/></li><li>Encourage students to say the sentence (e.g. 'My name is Tom'), then tap the character to check.<br/></li>

<li>Wave and say 'hello' to one of the characters on the screen, then ask 'what's your name?'.<br/></li><li>Encourage students to repeat the question.<br/></li><li>Encourage students to say the sentence (e.g. 'My name is Tom'), then tap the character to check.<br/></li><li>Point to the next character and encourage students to ask the question: 'What's your name?', then tap the text box to check.<br/></li>

<li>Wave and say 'hello' to one of the characters on the screen, then ask 'what's your name?'.<br/></li><li>Encourage students to repeat the question.<br/></li><li>Encourage students to say the sentence (e.g. 'My name is Tom'), then tap the character to check.<br/></li><li>Point to the next character and encourage students to ask the question: 'What's your name?', then tap the text box to check.<br/></li><li>Continue to have the students say the questions and answers for all characters on the board.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Pass the Ball</span><span style="font-size:10;"><br/>Hold a ball and say: 'My name is [own name]', then pass the ball to your co-teacher and ask: 'What's your name?'. Your co-teacher should respond: 'My name is [own name]'. Have students ask and answer the question in the same way, as they pass the ball around the room.<br/>Finally, invite students to the front of the class to introduce themselves, using the sentence frame: 'Hello. My name is ___'.</span></li>

<li>Explain to students that today we will make words by combining sounds.<br/></li>

<li>Explain to students that today we will make words by combining sounds.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> and model how to blend the sounds: Hold out your right hand and say the first sound (/</span><span style="font-size:10;">m</span><span style="font-size:10;">/). Then hold out your left and say the last sound (e.g. /</span><span style="font-size:10;">uffin</span><span style="font-size:10;">/). Finally, clap your hands together and say the whole word (e.g. '</span><span style="font-size:10;">muffin</span><span style="font-size:10;">').<br/></li>

<li>Explain to students that today we will make words by combining sounds.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> and model how to blend the sounds: Hold out your right hand and say the first sound (/</span><span style="font-size:10;">m</span><span style="font-size:10;">/). Then hold out your left and say the last sound (e.g. /</span><span style="font-size:10;">uffin</span><span style="font-size:10;">/). Finally, clap your hands together and say the whole word (e.g. '</span><span style="font-size:10;">muffin</span><span style="font-size:10;">').<br/></li><li>Have students do the same, then allow students to choose the matching picture.<br/></li>

<li>Explain to students that today we will make words by combining sounds.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> and model how to blend the sounds: Hold out your right hand and say the first sound (/</span><span style="font-size:10;">m</span><span style="font-size:10;">/). Then hold out your left and say the last sound (e.g. /</span><span style="font-size:10;">uffin</span><span style="font-size:10;">/). Finally, clap your hands together and say the whole word (e.g. '</span><span style="font-size:10;">muffin</span><span style="font-size:10;">').<br/></li><li>Have students do the same, then allow students to choose the matching picture.<br/></li><li>Invite a student who is participating well to tap the picture on the board.<br/></li>

<li>Explain to students that today we will make words by combining sounds.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> and model how to blend the sounds: Hold out your right hand and say the first sound (/</span><span style="font-size:10;">m</span><span style="font-size:10;">/). Then hold out your left and say the last sound (e.g. /</span><span style="font-size:10;">uffin</span><span style="font-size:10;">/). Finally, clap your hands together and say the whole word (e.g. '</span><span style="font-size:10;">muffin</span><span style="font-size:10;">').<br/></li><li>Have students do the same, then allow students to choose the matching picture.<br/></li><li>Invite a student who is participating well to tap the picture on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to hear a new word and guide students to blend the sounds in the same way.<br/></li>

<li>Explain to students that today we will make words by combining sounds.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> and model how to blend the sounds: Hold out your right hand and say the first sound (/</span><span style="font-size:10;">m</span><span style="font-size:10;">/). Then hold out your left and say the last sound (e.g. /</span><span style="font-size:10;">uffin</span><span style="font-size:10;">/). Finally, clap your hands together and say the whole word (e.g. '</span><span style="font-size:10;">muffin</span><span style="font-size:10;">').<br/></li><li>Have students do the same, then allow students to choose the matching picture.<br/></li><li>Invite a student who is participating well to tap the picture on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to hear a new word and guide students to blend the sounds in the same way.<br/></li><li>Have students choose the matching picture and invite a student to click it on the board.<br/></li>

<li>Explain to students that today we will make words by combining sounds.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> and model how to blend the sounds: Hold out your right hand and say the first sound (/</span><span style="font-size:10;">m</span><span style="font-size:10;">/). Then hold out your left and say the last sound (e.g. /</span><span style="font-size:10;">uffin</span><span style="font-size:10;">/). Finally, clap your hands together and say the whole word (e.g. '</span><span style="font-size:10;">muffin</span><span style="font-size:10;">').<br/></li><li>Have students do the same, then allow students to choose the matching picture.<br/></li><li>Invite a student who is participating well to tap the picture on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> to hear a new word and guide students to blend the sounds in the same way.<br/></li><li>Have students choose the matching picture and invite a student to click it on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>NEXT</b></span><span style="font-size:10;"> and continue with more words.<br/></span></li>

<li>Ask students if they can remember the word of the day, then tap the left curtain to check.<br/></li>

<li>Ask students if they can remember the word of the day, then tap the left curtain to check.<br/></li><li>Ask students if they can remember the sound of the day, then tap the middle curtain to check.<br/></li>

<li>Ask students if they can remember the word of the day, then tap the left curtain to check.<br/></li><li>Ask students if they can remember the sound of the day, then tap the middle curtain to check.<br/></li><li>Ask students if they can guess the letter of the day, then tap the right curtain to check.<br/></li>

<li>Ask students if they can remember the word of the day, then tap the left curtain to check.<br/></li><li>Ask students if they can remember the sound of the day, then tap the middle curtain to check.<br/></li><li>Ask students if they can guess the letter of the day, then tap the right curtain to check.<br/></li><li>Have students repeat the sentence</span><span style="font-size:10;"> 'M sounds like /m/'</span><span style="font-size:10;"> while doing the sound-action.</span></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class (optional).<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class (optional).<br/></li><li>Ask students to recall the letter of the day.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class (optional).<br/></li><li>Ask students to recall the letter of the day.<br/></li><li>Ask students to find the letter of the day in the alphabet on the board.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class (optional).<br/></li><li>Ask students to recall the letter of the day.<br/></li><li>Ask students to find the letter of the day in the alphabet on the board.<br/></li><li>Tap the letter of the day to enlarge it.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class (optional).<br/></li><li>Ask students to recall the letter of the day.<br/></li><li>Ask students to find the letter of the day in the alphabet on the board.<br/></li><li>Tap the letter of the day to enlarge it.<br/></li><li>Tap the </span><span style="font-size:10;">'M'</span><span style="font-size:10;"> and have students repeat: 'big</span><span style="font-size:10;"> M</span><span style="font-size:10;">'.<br/></li>

<li>Tell students that we can see the letters of the alphabet on the board.<br/></li><li>Tap </span><span style="font-size:10;"><b>PLAY</b></span><span style="font-size:10;"> and sing the alphabet song as a class (optional).<br/></li><li>Ask students to recall the letter of the day.<br/></li><li>Ask students to find the letter of the day in the alphabet on the board.<br/></li><li>Tap the letter of the day to enlarge it.<br/></li><li>Tap the </span><span style="font-size:10;">'M'</span><span style="font-size:10;"> and have students repeat: 'big</span><span style="font-size:10;"> M</span><span style="font-size:10;">'.<br/></li><li>Tap the '</span><span style="font-size:10;">m</span><span style="font-size:10;">' and have students repeat: 'small </span><span style="font-size:10;">m</span><span style="font-size:10;">'.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Jump and Crouch</span><span style="font-size:10;"><br/>Encourage students to say 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' and 'small m' as you point to the big and small letters on the board. Students should jump as they say 'big</span><span style="font-size:10;"> M</span><span style="font-size:10;">' and crouch as they say 'small </span><span style="font-size:10;">m</span><span style="font-size:10;">'.</span></li>

<li>Point to the first picture and have students say the word.<br/></li>

<li>Point to the first picture and have students say the word.<br/></li><li>Ask students if the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/></li>

<li>Point to the first picture and have students say the word.<br/></li><li>Ask students if the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/></li><li>If the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, ask students what letter we need, then drag a letter.<br/></li>

<li>Point to the first picture and have students say the word.<br/></li><li>Ask students if the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/></li><li>If the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, ask students what letter we need, then drag a letter.<br/></li><li>If the word does not start with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, allow students to respond: 'NO', then move to the next picture.<br/></li>

<li>Point to the first picture and have students say the word.<br/></li><li>Ask students if the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/></li><li>If the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, ask students what letter we need, then drag a letter.<br/></li><li>If the word does not start with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, allow students to respond: 'NO', then move to the next picture.<br/></li><li>Tap </span><span style="font-size:10;"><b>RESET</b></span><span style="font-size:10;"> to play again.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Sticky Ball</span><span style="font-size:10;"><br/>Students take turns to thow a 'sticky ball' at the pictures on the board. If they hit a word that starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, have the class say the word and first sound of the word (e.g. '</span><span style="font-size:10;">Milk</span><span style="font-size:10;">, /</span><span style="font-size:10;">m</span><span style="font-size:10;">/' or '</span><span style="font-size:10;">Milk</span><span style="font-size:10;"> starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/'). The student who threw the ball can then drag a letter to the picture. Continue, then tap </span><span style="font-size:10;"><b>RESET</b></span><span style="font-size:10;"> to play again.<br/></span></li>

<li>Point to the first picture and have students say the word.<br/></li>

<li>Point to the first picture and have students say the word.<br/></li><li>Ask students if the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/></li>

<li>Point to the first picture and have students say the word.<br/></li><li>Ask students if the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/></li><li>If the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, ask students: 'What letter sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/?'. Allow students to respond: '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/', then drag the picture.<br/></li>

<li>Point to the first picture and have students say the word.<br/></li><li>Ask students if the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/></li><li>If the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, ask students: 'What letter sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/?'. Allow students to respond: '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/', then drag the picture.<br/></li><li>If the word does not start with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, allow students to respond: 'NO', then move to the next picture.<br/></li>

<li>Point to the first picture and have students say the word.<br/></li><li>Ask students if the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/></li><li>If the word starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, ask students: 'What letter sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/?'. Allow students to respond: '</span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/', then drag the picture.<br/></li><li>If the word does not start with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/, allow students to respond: 'NO', then move to the next picture.<br/></li><li>Tap </span><span style="font-size:10;"><b>RESET</b></span><span style="font-size:10;"> to play again.<br/></span><span style="text-decoration: underline;font-size:10;">Play a Game: Group Grab</span><span style="font-size:10;"><br/>Invite four students to come and stand a few meters from the board. Have each student say a word that starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/. When you say: "3-2-1-GO!" all four students should run to the board and each drag a word that starts with /m/. Select some different students and play again.<br/></span></li>

<li>Encourage students to repeat the sentences on each page (clearly point to the word sas the students read them).<br/></li>

<li>Encourage students to repeat the sentences on each page (clearly point to the word sas the students read them).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li>

<li>Encourage students to repeat the sentences on each page (clearly point to the word sas the students read them).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li><li>Tap </span><span style="font-size:10;"><b>?</b></span><span style="font-size:10;"> to access comprehension questions for each page.<br/></li>

<li>Encourage students to repeat the sentences on each page (clearly point to the word sas the students read them).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li><li>Tap </span><span style="font-size:10;"><b>?</b></span><span style="font-size:10;"> to access comprehension questions for each page.<br/></li><li>Encourage students to find words beginning with </span><span style="font-size:10;">M</span><span style="font-size:10;">.<br/></li>

<li>Encourage students to repeat the sentences on each page (clearly point to the word sas the students read them).<br/></li><li>Tap the speaker to hear the sentence again.<br/></li><li>Tap </span><span style="font-size:10;"><b>?</b></span><span style="font-size:10;"> to access comprehension questions for each page.<br/></li><li>Encourage students to find words beginning with </span><span style="font-size:10;">M</span><span style="font-size:10;">.<br/></li><li>Invite students to come to the board and tap the words to collect them.</span></li>

<li>Have small groups of students take turns to read pages of the story.<br/></li>

<li>Have small groups of students take turns to read pages of the story.<br/></li><li>Tap the speaker to hear the sentence again.<br/>NOTE: It is usually best to group students of similar abilities </span><span style="font-size:10;"><b>together</b></span><span style="font-size:10;">. This ensures that all students in the group will be reading at a speed that is comfortable for them.</span></li>

<li>Rearrange tables and chairs, then have students sit at their desks with their workbooks open to the page shown on the board. Hand out pencils.<br/></li>

<li>Rearrange tables and chairs, then have students sit at their desks with their workbooks open to the page shown on the board. Hand out pencils.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the writing function on the board.<br/></li>

<li>Rearrange tables and chairs, then have students sit at their desks with their workbooks open to the page shown on the board. Hand out pencils.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the writing function on the board.<br/></li><li>Read the explainer box.<br/></span><span style="font-size:10;"></li>

<li>Rearrange tables and chairs, then have students sit at their desks with their workbooks open to the page shown on the board. Hand out pencils.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the writing function on the board.<br/></li><li>Read the explainer box.<br/></span><span style="font-size:10;"></li><li>Draw attention to the monkey and ask: 'Is the monkey on the motorcycle?'. Discuss with the class (yes, it is), then write a check in the box by the monkey. Have students do the same in their workbooks.<br/></li>

<li>Rearrange tables and chairs, then have students sit at their desks with their workbooks open to the page shown on the board. Hand out pencils.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the writing function on the board.<br/></li><li>Read the explainer box.<br/></span><span style="font-size:10;"></li><li>Draw attention to the monkey and ask: 'Is the monkey on the motorcycle?'. Discuss with the class (yes, it is), then write a check in the box by the monkey. Have students do the same in their workbooks.<br/></li><li>Draw attention to the mouse and ask: 'Is the mouse on the motorcycle?'. Discuss with the class (no, it's not), then show that we do NOT write a check for the mouse.<br/></li>

<li>Rearrange tables and chairs, then have students sit at their desks with their workbooks open to the page shown on the board. Hand out pencils.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the writing function on the board.<br/></li><li>Read the explainer box.<br/></span><span style="font-size:10;"></li><li>Draw attention to the monkey and ask: 'Is the monkey on the motorcycle?'. Discuss with the class (yes, it is), then write a check in the box by the monkey. Have students do the same in their workbooks.<br/></li><li>Draw attention to the mouse and ask: 'Is the mouse on the motorcycle?'. Discuss with the class (no, it's not), then show that we do NOT write a check for the mouse.<br/></li><li>Continue to guide students through all the items, as they complete the activity in their workbooks.</span></li>

<li>Ask: 'What is the title of our story today?' and allow students to respond.<br/></li>

<li>Ask: 'What is the title of our story today?' and allow students to respond.<br/></li><li>Demonstrate how to trace the title, then have students do it themselves, in their workbooks.<br/></span><span style="font-size:10;"></li>

<li>Ask: 'What is the title of our story today?' and allow students to respond.<br/></li><li>Demonstrate how to trace the title, then have students do it themselves, in their workbooks.<br/></span><span style="font-size:10;"></li><li>Discuss with students whether or not they enjoyed the story.<br/></li>

<li>Ask: 'What is the title of our story today?' and allow students to respond.<br/></li><li>Demonstrate how to trace the title, then have students do it themselves, in their workbooks.<br/></span><span style="font-size:10;"></li><li>Discuss with students whether or not they enjoyed the story.<br/></li><li>Demonstrate that if we did NOT like the story, we can color just one star. But if we REALLY liked the story, we can color all five stars.<br/></li>

<li>Ask: 'What is the title of our story today?' and allow students to respond.<br/></li><li>Demonstrate how to trace the title, then have students do it themselves, in their workbooks.<br/></span><span style="font-size:10;"></li><li>Discuss with students whether or not they enjoyed the story.<br/></li><li>Demonstrate that if we did NOT like the story, we can color just one star. But if we REALLY liked the story, we can color all five stars.<br/></li><li>Have students give their own rating by coloring the stars in their workbooks.<br/></li>

<li>Ask: 'What is the title of our story today?' and allow students to respond.<br/></li><li>Demonstrate how to trace the title, then have students do it themselves, in their workbooks.<br/></span><span style="font-size:10;"></li><li>Discuss with students whether or not they enjoyed the story.<br/></li><li>Demonstrate that if we did NOT like the story, we can color just one star. But if we REALLY liked the story, we can color all five stars.<br/></li><li>Have students give their own rating by coloring the stars in their workbooks.<br/></li><li>Ask students to remember all the animals they saw in the story (moose, mouse, monkey). Explain that these animals are characters in the story.<br/></li>

<li>Ask: 'What is the title of our story today?' and allow students to respond.<br/></li><li>Demonstrate how to trace the title, then have students do it themselves, in their workbooks.<br/></span><span style="font-size:10;"></li><li>Discuss with students whether or not they enjoyed the story.<br/></li><li>Demonstrate that if we did NOT like the story, we can color just one star. But if we REALLY liked the story, we can color all five stars.<br/></li><li>Have students give their own rating by coloring the stars in their workbooks.<br/></li><li>Ask students to remember all the animals they saw in the story (moose, mouse, monkey). Explain that these animals are characters in the story.<br/></li><li>Discuss with students which character they liked the most.<br/>Based on the responses, demonstrate drawing one of the characters on the board.<br/></li>

<li>Ask: 'What is the title of our story today?' and allow students to respond.<br/></li><li>Demonstrate how to trace the title, then have students do it themselves, in their workbooks.<br/></span><span style="font-size:10;"></li><li>Discuss with students whether or not they enjoyed the story.<br/></li><li>Demonstrate that if we did NOT like the story, we can color just one star. But if we REALLY liked the story, we can color all five stars.<br/></li><li>Have students give their own rating by coloring the stars in their workbooks.<br/></li><li>Ask students to remember all the animals they saw in the story (moose, mouse, monkey). Explain that these animals are characters in the story.<br/></li><li>Discuss with students which character they liked the most.<br/>Based on the responses, demonstrate drawing one of the characters on the board.<br/></li><li>Have students draw their own favorite character in their workbooks. (Erase your own drawing on the board before students draw their own).</span></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li><li>Begin by demonstrating the correct way to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li><li>Begin by demonstrating the correct way to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'.<br/></li><li>Write the letter again, making some silly mistakes (consider stroke order, proportions and position on the lines).<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li><li>Begin by demonstrating the correct way to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'.<br/></li><li>Write the letter again, making some silly mistakes (consider stroke order, proportions and position on the lines).<br/></li><li>Finally, demonstrate again the correct way to write 'big</span><span style="font-size:10;"> M</span><span style="font-size:10;">'.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li><li>Begin by demonstrating the correct way to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'.<br/></li><li>Write the letter again, making some silly mistakes (consider stroke order, proportions and position on the lines).<br/></li><li>Finally, demonstrate again the correct way to write 'big</span><span style="font-size:10;"> M</span><span style="font-size:10;">'.<br/></li><li>Repeat all of the above for 'small </span><span style="font-size:10;">m</span><span style="font-size:10;">'.<br/></li>

<li>Ask students: 'What is the letter of the day?' and have them respond.<br/></li><li>Tell students that we will learn how to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'. <br/></li><li>Tap the 'big M' on the board and allow students to see the stroke order.<br/></li><li>Have students stand up and use their fingers to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">' in the air. Use the simple instructions:  '</span><span style="font-size:10;">Down, down, up, down</span><span style="font-size:10;">'.<br/></li><li>Tap the ' big </span><span style="font-size:10;">M</span><span style="font-size:10;">' on the board again and repeat.<br/></li><li>Tap the </span><span style="font-size:10;"><b>FUN</b></span><span style="font-size:10;"> button and have students write in the air again as they watch the letter strokes on the board.<br/></li><li>Tap the </span><span style="font-size:10;"><b>PEN</b></span><span style="font-size:10;"> in the toolbar to enable the pen function.<br/></li><li>Begin by demonstrating the correct way to write 'big </span><span style="font-size:10;">M</span><span style="font-size:10;">'.<br/></li><li>Write the letter again, making some silly mistakes (consider stroke order, proportions and position on the lines).<br/></li><li>Finally, demonstrate again the correct way to write 'big</span><span style="font-size:10;"> M</span><span style="font-size:10;">'.<br/></li><li>Repeat all of the above for 'small </span><span style="font-size:10;">m</span><span style="font-size:10;">'.<br/></li><li>Stroke Instructions for 'small</span><span style="font-size:10;"> m</span><span style="font-size:10;">': </span><span style="font-size:10;"> 'Down, over, over'.</span></li>

<li>Tap the PEN in the toolbar to enable the pen function.<br/></li>

<li>Tap the PEN in the toolbar to enable the pen function.<br/></li><li>Demonstrate and explain how students should complete the page in their workbooks. As you are doing so, ask the following questions:<br/>Q: What is the letter of the day?' A: </span><span style="font-size:10;">M</span><span style="font-size:10;"><br/>Q: What does</span><span style="font-size:10;"> M</span><span style="font-size:10;"> sound like?  A: </span><span style="font-size:10;">M</span><span style="font-size:10;"> sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/>Q: What does '</span><span style="font-size:10;">milk</span><span style="font-size:10;">' start with'? A: </span><span style="font-size:10;">Milk</span><span style="font-size:10;"> starts with /</span><span style="font-size:10;">m</span><span style="font-size:10;">/.<br/>Q: What letter should we write? A: </span><span style="font-size:10;">M</span></li>

<li>Tap the PEN in the toolbar to enable the pen function.<br/></li>

<li>Tap the PEN in the toolbar to enable the pen function.<br/></li><li>Demonstrate and explain how students should complete the page in their workbooks. As you are doing so, ask the following questions:<br/>Q: What is this? A: </span><span style="font-size:10;">Milk</span><span style="font-size:10;"><br/>Q: What sound does 'milk' start with?  A: </span><span style="font-size:10;">Milk </span><span style="font-size:10;">starts with</span><span style="font-size:10;"> /m/.</span><span style="font-size:10;"><br/>Q: What letter sounds like /</span><span style="font-size:10;">m</span><span style="font-size:10;">/</span><span style="font-size:10;">? A: </span><span style="font-size:10;">M</span></li>

week_1

week_2

